"""ceshi

Revision ID: fce187c95ccf
Revises: 
Create Date: 2022-11-22 13:04:58.221380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fce187c95ccf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mock_lists')
    op.drop_table('mcok_interfaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcok_interfaces',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='接口id'),
    sa.Column('service', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=50), nullable=False, comment='服务名'),
    sa.Column('interface_name', mysql.VARCHAR(charset='utf8', collation='utf8_bin', length=50), nullable=False, comment='接口名'),
    sa.Column('interface_mock_id', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True, comment='接口mock数据，为0为随机mock'),
    sa.Column('is_delete', mysql.INTEGER(), autoincrement=False, nullable=True, comment='是否删除:0-正常；1-删除'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('interface_path', mysql.VARCHAR(collation='utf8_bin', length=300), nullable=False, comment='接口url'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('mock_lists',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='mockid'),
    sa.Column('mock_interface_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=False, comment='mock接口id'),
    sa.Column('mock_name', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=True, comment='mock名称'),
    sa.Column('mock_data', mysql.VARCHAR(collation='utf8_bin', length=3000), nullable=True, comment='mock数据'),
    sa.Column('is_delete', mysql.INTEGER(), autoincrement=False, nullable=True, comment='是否删除:0-正常；1-删除'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
